language: node_js

node_js:
  - "node"

script: npm run build

before_deploy:
  - sed -i 'dist\/docs/d' .gitignore
  - sed -i 'dist\/app\*/d' .gitignore
  - sed -i 'index.html/d' .gitignore

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
